name: Deploy AgentHub React to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'agenthub-react/**'
      - '.github/workflows/azure-deploy.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: AgentHubDev
  AZURE_WEBAPP_PACKAGE_PATH: './agenthub-react/dist'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './agenthub-react/package-lock.json'

    - name: Install dependencies
      run: |
        cd agenthub-react
        npm ci

    - name: Build for production
      run: |
        cd agenthub-react
        npm run build
      env:
        VITE_API_URL: https://workflowcanvasapi.azurewebsites.net/api
        VITE_APP_ENV: production
        VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY }}
        VITE_OPENAI_MODEL: gpt-4o-mini

    - name: Create deployment package
      run: |
        cd agenthub-react/dist
        zip -r ../../deploy.zip .
        cd ../..

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: deploy.zip

    - name: Configure startup command
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az webapp config set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group DEV-InternalProject \
            --startup-file "pm2 serve /home/site/wwwroot --no-daemon --spa"

    - name: Logout from Azure
      run: az logout